SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6556A2FDDAA2E551}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66BF19327F5DD724}" {
     m_bEnabled 0
    }
   }
  }
 }
}