SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{698B46AD02A0C6DB}" {
   m_aEntityDataList {
    SCR_ArsenalItem "{698B46AD02A0C60A}" {
     m_eItemType HANDWEAR
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{696EBE0C08CEB69F}" {
   m_aEntityDataList {
    SCR_ArsenalItem "{696EBE0C08CEB6FF}" {
     m_eItemType HANDWEAR
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{695AA2AD11EB273C}" {
   m_aEntityDataList {
    SCR_ArsenalItem "{695AA2AD11EB2723}" {
     m_eItemType HANDWEAR
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6968113AA3FA7AE6}" {
   m_aEntityDataList {
    SCR_ArsenalItem "{6968113AA3FA7A4B}" {
     m_eItemType HANDWEAR
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6968113AA26F28EB}" {
   m_aEntityDataList {
    SCR_ArsenalItem "{6968113AA26F2854}" {
     m_eItemType HANDWEAR
    }
   }
  }
 }
}