SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6556A2FE10697152}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66BF22517976D122}" {
     m_bEnabled 0
    }
   }
  }
 }
}