SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{61835C01E90BB7D5}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{61835C023A20447B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C0232DDB659}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C025850E36B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C025A0875B2}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C0248479D3A}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C0245AF3B13}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6216FB8C0F292C64}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C0247A731AA}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C0241C12001}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C0243AEDD6C}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C0268919BDE}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C026B7EABDD}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C02653AD200}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C0266A83C23}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C02617DA12A}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{61835C0263272D2B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64F6D4B510DDC994}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64F6D4B519E281B0}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{61835C01E373CF53}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{61835C021732E80B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{62D2F3D1EB0EA86A}" {
     m_bEnabled 0
    }
   }
  }
 }
}