SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C9E82F29B327997}" {
   m_aMultiLists {
    SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
     m_aEntities {
      SCR_EntityCatalogEntry "{605098A545E912FC}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogEntry "{5D23482664F150D9}" {
       m_bEnabled 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiList "{5C68A0EEB3F124F9}" : "{5F7EC52FC40A03E2}Configs/EntityCatalog/US/InventoryItems_EntityCatalog_US.conf" {
   m_aMultiLists {
    SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
     m_aEntities {
      SCR_EntityCatalogInventoryItem "{69062C2122B901A7}" {
      }
      SCR_EntityCatalogInventoryItem "{6A0B49B5AC710D28}" {
       m_aEntityDataList {
        SCR_ArsenalItem "{69062C2122B90168}" {
         m_iSupplyCost 0
        }
       }
      }
     }
    }
   }
  }
 }
}