SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0E9AFE1E631}" : "{5F7EC52FC40A03E2}Configs/EntityCatalog/US/InventoryItems_EntityCatalog_US.conf" {
   m_aMultiLists {
    SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
     m_aEntities {
      SCR_EntityCatalogInventoryItem "{6A0B49B5AC710D28}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{6A0B49B4800F1D6E}" {
       m_sEntityPrefab "{5C5A165F517043DA}Prefabs/Characters/Armbands/Tape_Large/Factions/Armband_Tape_Large_USSR_FriendlyOnly.et"
       m_aEntityDataList {
        SCR_ArsenalItem "{6A0F222FEE0D1DD2}" {
         m_eItemType HANDWEAR
         m_iSupplyCost 0
        }
       }
      }
      SCR_EntityCatalogInventoryItem "{69FEDA372B41CA0A}" {
       m_sEntityPrefab "{F159C0338500CDDD}Prefabs/Characters/Armbands/Tape_Large/Armband_Tape_Large_Red.et"
       m_bEnabled 0
      }
     }
    }
    SCR_EntityCatalogMultiListEntry "{69EB292D690855EC}" {
     m_aEntities {
      SCR_EntityCatalogInventoryItem "{69EB292D6915BB9B}" {
       m_sEntityPrefab "{B343AB76B0725657}Prefabs/Items/Equipment/Radios/Radio_R187P1_OLD.et"
      }
     }
    }
   }
  }
 }
}